# Generated by Django 4.2.11 on 2024-05-08 13:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_verify_cancelation_booking_verify_cancelation_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
