# Generated by Django 4.2.11 on 2024-05-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_cancelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelbooking',
            name='id',
        ),
        migrations.AddField(
            model_name='cancelbooking',
            name='booking',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.booking'),
            preserve_default=False,
        ),
    ]
