# Generated by Django 4.2.11 on 2024-05-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_verify_cancelation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='verify_cancellation_policy',
            field=models.BooleanField(default=False, help_text='Please check this box to confirm you have read and agree to the cancellation policy', verbose_name='Cancellation Policy Agreement | You Have Read And Understand That You Can Need To Cancel Your Reservation Atleast 4 Hours Before Your Reserved Time'),
        ),
    ]
